USE SIXNINE;

DROP TABLE `TWO_QUESTION`;
DROP TABLE four_question;

CREATE TABLE four_question (
# QUESTION_NUM INT NOT NULL AUTO_INCREMENT,
QUESTION VARCHAR(255) NOT NULL UNIQUE,
correctAnswer INT,
Q1 VARCHAR(255),
Q2 VARCHAR(255),
Q3 VARCHAR(255),
Q4 VARCHAR(255)
# PRIMARY KEY (QUESTION_NUM)
);

CREATE TABLE `TWO_QUESTION` (
# QUESTION_NUM INT NOT NULL AUTO_INCREMENT,
QUESTION VARCHAR(255) NOT NULL UNIQUE,
correctAnswer INT,
Q1 VARCHAR(255),
Q2 VARCHAR(255)
# PRIMARY KEY (QUESTION_NUM)
);
